version: "2"

linters:
  disable:
    - errcheck

  settings:
    staticcheck:
      checks:
        - all
        - -SA1019   # deprecated APIs
        - -ST1005   # error string formatting
        - -ST1000   # package comments
        - -ST1003   # naming conventions (IP, URL, HTTP, etc)