sites:
  - name: k8s-1
    token: XXX
    site-manager: https://site-manager.k8s-1.netcracker.com/sitemanager
    cacert: ca-k8s-1-selfsigned.cer 
  - name: k8s-2
    token: XXX
    site-manager: https://site-manager.k8s-2.netcracker.com/sitemanager
sm-client:
  http_auth: True
  service_default_timeout: 400
