FROM --platform=$BUILDPLATFORM python:3.10.14-alpine3.20

ARG SM_USER=smuser
ARG SM_UID=1001

USER root

COPY smclient.py version sm-client /app/
COPY sm_client/ /app/sm_client/
COPY common/ /app/common/

COPY requirements-sc.txt /app/requirements.txt

WORKDIR /app/

RUN apk update && \
    apk upgrade && \
    apk add bash && \
    adduser -D -u "${SM_UID}" "${SM_USER}" && \
    pip install --upgrade pip==24.* --no-cache-dir && \
    pip install -r requirements.txt --no-cache-dir && \
    chmod 755 /app/sm-client

USER "${SM_USER}"

CMD ["python", "sm-client"]
