FROM python:3.8-slim

ARG SM_USER=smuser
ARG SM_UID=1001

USER root

COPY site-manager /app/
COPY modules /app/modules
COPY utils.py /app/
COPY requirements-sm.txt /app/requirements.txt

WORKDIR /app/

RUN useradd -r -u "${SM_UID}" "${SM_USER}" && \
    pip install --upgrade pip && \
    pip install wheel==0.37.0 && \
    pip install -r requirements.txt

USER "${SM_USER}"

CMD ["python", "site-manager"]
