#!/usr/bin/env python3
import graphlib
import logging
import utils


def get_all_services(sm_dict):
    """
    Method for definition of list of all services in kubernetes cluster managed by site-manager

    :param dict sm_dict: the dictionary generated by get_sitemanagers_dict() and based on CRs from kubernetes clusters
    """

    return list(set([ i for i in sm_dict["services"].keys() ]))


def get_services_to_run(run_services, skip_services, all_services):
    """
    Method for definition of list of services to be processed

    :param list run_services: the list of services that defined by parameter run-services
    :param list skip_services: the list of services that defined by parameter skip-services
    :param list all_services: the list of all services from kubernetes clusters managed by site-manager
    """

    if len(run_services) != 0:
        services_to_run = []
        for item in run_services:
            if item in all_services:
                services_to_run.append(item)
            else:
                logging.fatal(f"Service {item} does not exist in provided kubernetes clusters")
                exit(1)

    elif len(skip_services) != 0:
        services_to_run = all_services.copy()
        for item in skip_services:
            if item in all_services:
                services_to_run.remove(item)
            else:
                logging.fatal(f"Service {item} does not exist in provided kubernetes clusters")
                exit(1)

    else:
        services_to_run = all_services.copy()

    return services_to_run


def get_status(service, *args, **kwargs):
    """
    Method that collects complete information about the state of the service
    @param dict service: service's CR
    """

    output = dict()
    _, status, _ = utils.io_make_http_json_request(service['parameters']["serviceEndpoint"],token=utils.SM_AUTH_TOKEN)
    output["mode"] = status.get("mode", "--")
    output["status"] = status.get("status", "--")
    output["message"] = status.get("message", "")
    if service['parameters'].get("healthzEndpoint", "") != "":
        _, healthz, _ = utils.io_make_http_json_request(service['parameters']["healthzEndpoint"],token=utils.SM_AUTH_TOKEN)
        output["healthz"] = healthz.get("status", "--")
    else:
        output["healthz"] = "--"

    return output


def get_status_with_deps(service, sm_dict, *args, **kwargs):
    """
    Method that collects complete information about the state of the service with dependencies if needed
    @param str service: name of needed service
    @param dict sm_dict: services' CRs
    """
    with_deps = kwargs.get('with_deps', False)

    # Collect services with deps
    tmp_sm_dict = {}

    def visit_service(services, parent_service=None):
        for service_name in services:
            if service_name not in sm_dict['services']:
                logging.error(f"Found not exist dependency: {service_name} in {parent_service} CR")
                raise utils.ProcedureException(output={
                    "message": "Dependency defined in CR doesn't exist",
                    "wrong-service": service_name,
                    "problem-cr": parent_service
                })
            if service_name not in tmp_sm_dict and with_deps:
                tmp_sm_dict[service_name] = sm_dict['services'][service_name]
                visit_service(sm_dict['services'][service_name]['before'], service_name)
                visit_service(sm_dict['services'][service_name]['after'], service_name)

    visit_service([service])

    try:
        utils.build_after_before_graph(tmp_sm_dict).prepare()
    except graphlib.CycleError:
        # TODO: How to understand where the cycle is?
        raise utils.ProcedureException(output={
            "message": "Found cycle in service dependencies"
            #"wrong-service": "---",
            #"cycled-services": visited_services_stack
        })

    def collect_statuses_tree_for_services(services):
        output = dict()
        for service_name in services:
            # Get status for service
            cr = sm_dict['services'][service_name]
            output[service_name] = get_status(cr, args, kwargs)

            # Get dependencies if needed
            if with_deps:
                output[service_name]['deps'] = {
                    'before': collect_statuses_tree_for_services(cr['before']),
                    'after': collect_statuses_tree_for_services(cr['after'])
                }
        return output

    return collect_statuses_tree_for_services([service])
