{{ if .Values.createClusterAdminEntities }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}
rules:
  - apiGroups: ["{{ .Values.env.SM_GROUP }}", "qubership.org"]
    resources: ["sitemanagers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["{{ .Values.env.SM_GROUP }}", "qubership.org"]
    resources: ["sitemanagers/status"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
{{ end }}
