{{ if .Values.ingress.create }}
apiVersion: {{ include "site-manager.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
  {{- if .Values.ingress.name }}
  - host: {{ .Values.ingress.name }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
  {{- if eq ( include "site-manager.ingress.apiVersion" . ) "networking.k8s.io/v1beta1" }}
          serviceName: {{ .Chart.Name }}
          servicePort: 443
  {{- else if eq ( include "site-manager.ingress.apiVersion" . ) "networking.k8s.io/v1" }}
          service:
            name: {{ .Chart.Name }}
            port:
              number: 443
  {{- end }}
{{ end }}