{{ if .Values.paasGeoMonitor.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas-geo-monitor
  {{- if .Values.SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/instance: '{{ cat (coalesce .Values.DEPLOYMENT_RESOURCE_NAME .Values.SERVICE_NAME) "-" .Values.NAMESPACE | nospace | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Values.ARTIFACT_DESCRIPTOR_VERSION }}'
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    app.kubernetes.io/technology: go
  {{- end }}
spec:
  selector:
    matchLabels:
      app: paas-geo-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: paas-geo-monitor
        {{- if .Values.SERVICE_NAME }}
        app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
        app.kubernetes.io/instance: '{{ cat (coalesce .Values.DEPLOYMENT_RESOURCE_NAME .Values.SERVICE_NAME) "-" .Values.NAMESPACE | nospace | trunc 63 | trimSuffix "-" }}'
        app.kubernetes.io/version: '{{ .Values.ARTIFACT_DESCRIPTOR_VERSION }}'
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: '{{ .Values.SERVICE_NAME }}'
        app.kubernetes.io/technology: go
        {{- end }}
    spec:
      serviceAccount: paas-geo-monitor
      automountServiceAccountToken: false
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{ include  "securityContext" . }}
      containers:
      - name: paas-geo-monitor
        securityContext:
          runAsNonRoot: true
          {{- if eq (default "" .Values.PAAS_PLATFORM) "KUBERNETES" }}
          runAsUser: 1001
          runAsGroup: 1001
          {{- end }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
        image: {{ template "find_image" (dict "SERVICE_NAME" "paas-geo-monitor" "vals" .Values "default" .Values.paasGeoMonitor.image) }}
        imagePullPolicy: Always
        args:
          - "--config=/config/config.yaml"
        env:
          - name: PING_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PAAS_PING_PEERS
            value: "{{ .Values.paasGeoMonitor.env.PAAS_PING_PEERS }}"
          - name: PAAS_PING_TIME
            value: "{{ .Values.paasGeoMonitor.env.PAAS_PING_TIME }}"
          - name: PAAS_DEBUG
            value: "{{ .Values.paasGeoMonitor.env.PAAS_DEBUG }}"
          - name: PAAS_BGP_METRICS
            value: "{{ .Values.paasGeoMonitor.env.PAAS_BGP_METRICS }}"
          - name: PAAS_BGP_CHECK_PERIOD
            value: "{{ .Values.paasGeoMonitor.env.PAAS_BGP_CHECK_PERIOD }}"
          - name: PAAS_BGP_CHECK_TIMEOUT
            value: "{{ .Values.paasGeoMonitor.env.PAAS_BGP_CHECK_TIMEOUT }}"
          - name: GOMEMLIMIT
            value: 95MiB
        ports:
          - containerPort: {{ include "paas-geo-monitor.port" . }}
            protocol: TCP
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: serviceaccount-token
            readOnly: true
          - mountPath: /tmp
            name: tmp
        resources:
          limits:
              cpu: "20m"
              # If you change memory limit, you should add GOMEMLIMIT env with 90-95% of new value
              memory: "100Mi"
          requests:
              cpu: "20m"
              memory: "100Mi"
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ include "paas-geo-monitor.port" . }}
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ include "paas-geo-monitor.port" . }}
            scheme: HTTP
          timeoutSeconds: 2
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
        - name: config
          configMap:
            name: paas-geo-monitor-cfg
        - name: serviceaccount-token
          projected:
            defaultMode: 0444
            sources:
            - serviceAccountToken:
                expirationSeconds: 3607
                path: token
            - configMap:
                name: kube-root-ca.crt
                items:
                - key: ca.crt
                  path: ca.crt
            - downwardAPI:
                items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
{{ end }}
