{{ if .Values.paas_geo_monitor.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: paas-geo-monitor-cfg
data:
  config.yaml: |
{{- toYaml .Values.paas_geo_monitor.config | nindent 4 }}
{{ end }}