{{ if .Values.paasGeoMonitor.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paas-geo-monitor
spec:
  selector:
    matchLabels:
      app: paas-geo-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: paas-geo-monitor
    spec:
      serviceAccount: paas-geo-monitor
      automountServiceAccountToken: false
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: paas-geo-monitor
        {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: {{ .Values.paasGeoMonitor.image}}
        imagePullPolicy: Always
        args:
          - "--config=/config/config.yaml"
        env:
          - name: PING_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PAAS_PING_PEERS
            value: "{{ .Values.paasGeoMonitor.env.PAAS_PING_PEERS }}"
          - name: PAAS_PING_TIME
            value: "{{ .Values.paasGeoMonitor.env.PAAS_PING_TIME }}"
          - name: PAAS_DEBUG
            value: "{{ .Values.paasGeoMonitor.env.PAAS_DEBUG }}"
          - name: PAAS_BGP_METRICS
            value: "{{ .Values.paasGeoMonitor.env.PAAS_BGP_METRICS }}"
          - name: PAAS_BGP_CHECK_PERIOD
            value: "{{ .Values.paasGeoMonitor.env.PAAS_BGP_CHECK_PERIOD }}"
          - name: PAAS_BGP_CHECK_TIMEOUT
            value: "{{ .Values.paasGeoMonitor.env.PAAS_BGP_CHECK_TIMEOUT }}"
          - name: GOMEMLIMIT
            value: 135MiB
        ports:
          - containerPort: {{ include "paas-geo-monitor.port" . }}
            protocol: TCP
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: serviceaccount-token
            readOnly: true
        resources:
          limits:
              cpu: "300m"
              # If you change memory limit, you should add GOMEMLIMIT env with 90-95% of new value
              memory: "150Mi"
          requests:
              cpu: "50m"
              memory: "50Mi"
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ include "paas-geo-monitor.port" . }}
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ include "paas-geo-monitor.port" . }}
            scheme: HTTP
          timeoutSeconds: 2
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: config
          configMap:
            name: paas-geo-monitor-cfg
        - name: serviceaccount-token
          projected:
            defaultMode: 0444
            sources:
            - serviceAccountToken:
                expirationSeconds: 3607
                path: token
            - configMap:
                name: kube-root-ca.crt
                items:
                - key: ca.crt
                  path: ca.crt
            - downwardAPI:
                items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
{{ end }}
