{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- if ge (int .Capabilities.KubeVersion.Minor) 24 }}
secrets:
- name: {{ .Values.serviceAccount.name }}-token
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
  name: {{ .Values.serviceAccount.name }}-token
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
