apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sitemanagers.netcracker.com
spec:
  group: netcracker.com
  names:
    kind: SiteManager
    listKind: SiteManagerList
    plural: sitemanagers
    singular: sitemanager
  scope: Namespaced
  versions:
  - name: v3
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              sitemanager:
                properties:
                  module:
                    type: string
                  after:
                    items:
                      type: string
                    type: array
                    default: []
                  before:
                    items:
                      type: string
                    type: array
                    default: []
                  sequence:
                    items:
                      type: string
                    type: array
                    default: []
                  allowedStandbyStateList:
                    items:
                      type: string
                    type: array
                    default: ["up"]
                  timeout:
                    type: integer
                    minimum: 10
                    maximum: 1000
                  parameters:
                    type: object
                    properties:
                      serviceEndpoint:
                        type: string
                      ingressEndpoint:
                        type: string
                      healthzEndpoint:
                        type: string
                required:
                - module
                type: object
            type: object
          status:
            properties:
              siteManagerStatus:
                properties:
                  status:
                    type: string
                type: object
            type: object
        type: object
  - name: v2
    served: true
    storage: false
    deprecated: true
    deprecationWarning: >-
      netcracker.com/v2 SiteManager is deprecated; use v3 and see actual
      version on
      https://github.com/Netcracker/DRNavigator#custom-resource-for-stateful
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              sitemanager:
                properties:
                  module:
                    type: string
                  after:
                    items:
                      type: string
                    type: array
                    default: []
                  before:
                    items:
                      type: string
                    type: array
                    default: []
                  sequence:
                    items:
                      type: string
                    type: array
                    default: []
                  allowedStandbyStateList:
                    items:
                      type: string
                    type: array
                    default: ["up"]
                  timeout:
                    type: integer
                    minimum: 10
                    maximum: 1000
                  parameters:
                    type: object
                    properties:
                      serviceEndpoint:
                        type: string
                      ingressEndpoint:
                        type: string
                      healthzEndpoint:
                        type: string
                required:
                - module
                type: object
            type: object
          status:
            properties:
              siteManagerStatus:
                properties:
                  status:
                    type: string
                type: object
            type: object
        type: object
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1"]
      clientConfig:
        service:
          namespace: site-manager
          name: site-manager
          path: /convert
        caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVTUw3MHg1Rms0U1plcHY4b1lsRXk5Umx5UEpzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tVMDBnYzJWeWRtbGpaVEFlRncweU1qQTVNVFl3TmpJNE16ZGFGdzB5TkRBNQpNVFV3TmpJNE16ZGFNQlV4RXpBUkJnTlZCQU1NQ2xOTklITmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEWS84SzhxY0VrZHQ0YWJ1eDFjSzJJcDdtMTNUOXg0MmNHbHFjeGNsVisKcUhrVVh4WlpheFhnOE5MZ29OMVVrTE1yT2VSSUtuMDdLaVc4QUJxMmxQYnhxYVJ0TWVIOVZFMFJqT3lHMlZHRQpJYUZMMFpLTXZkVUlsMzdwbkdHQlNZV2NlMlZGVnpHNnhJS0pBTU5zMDdyOWVibHFkSTlCYXJPblk0bi9remEyClNhUlZWcVBwWXJkbVRITE1qMnJVOFZ5ZlBrdTQ4Y0NVUVVHMUk4SDRxcnEzOFlja0xWQlJMYjNoSkxTYVNNOWMKcjlZS3NmcWJmYktEVDhibUpPbzlqQ2RJa1JBQ3ZBNlowQ05DUmd2YU95OVVhRTNaSlFVTDJBWldsWFNXa3RCRApqNVBGeUUwdS9qaCt3bmIwQ1VRYk16Y2UwcDhyVGUyQit2OVppYWJBSXVsakFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlNxeUk1OFptMzh6QUJwb1FoNVVuUHRUbzgvS1RBZkJnTlZIU01FR0RBV2dCU3F5STU4Wm0zOHpBQnAKb1FoNVVuUHRUbzgvS1RBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFERApSUVMzRjNDSzFiSG1jWkgydHFtZkYzTDJ3WlJqaXUxYkJGdHFKbUtEVVpjR281NlMxcG83bUFYeUVmYWJhOXBVCk5OM3czRXhzWVp6YytwSUFwS3kxNkZkenRWUHJ2RkpWUkpXd2JxQkVmNUFBQmhsNzRmeEZXZmxWeStscnd0WlUKTG5seFYzVm9jT2txVU5UZzBUTWNOTDFEb3dIOEZ4cTZicWthNUlyVk5CL0xFVkpjbE50RVRnb3hOMGVHc01neQpuY2V4VFZ2cDZnZmhYaEw2aGFWODA3RFhSWFJOZlQ1MVh3Yyt6N2I1MVJhR2wwRWJINFpySXRmamFzaWtZbEpYCnRyZjg1TE91QmFaalp4aFBSaXo0eS9VcnA0anhqdzNaZTFaUkZDVlpmTmJteXJ5MWliRUVuMFlRcmtpTG92RGQKTlNmRHVtV2c0dVZwUHg2VVRSM3EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "site-manager-crd-validating-webhook-configuration"
webhooks:
- name: "site-manager-crd-validating-webhook.netcracker.com"
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      namespace: site-manager
      name: site-manager
      path: /validate
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVTUw3MHg1Rms0U1plcHY4b1lsRXk5Umx5UEpzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tVMDBnYzJWeWRtbGpaVEFlRncweU1qQTVNVFl3TmpJNE16ZGFGdzB5TkRBNQpNVFV3TmpJNE16ZGFNQlV4RXpBUkJnTlZCQU1NQ2xOTklITmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEWS84SzhxY0VrZHQ0YWJ1eDFjSzJJcDdtMTNUOXg0MmNHbHFjeGNsVisKcUhrVVh4WlpheFhnOE5MZ29OMVVrTE1yT2VSSUtuMDdLaVc4QUJxMmxQYnhxYVJ0TWVIOVZFMFJqT3lHMlZHRQpJYUZMMFpLTXZkVUlsMzdwbkdHQlNZV2NlMlZGVnpHNnhJS0pBTU5zMDdyOWVibHFkSTlCYXJPblk0bi9remEyClNhUlZWcVBwWXJkbVRITE1qMnJVOFZ5ZlBrdTQ4Y0NVUVVHMUk4SDRxcnEzOFlja0xWQlJMYjNoSkxTYVNNOWMKcjlZS3NmcWJmYktEVDhibUpPbzlqQ2RJa1JBQ3ZBNlowQ05DUmd2YU95OVVhRTNaSlFVTDJBWldsWFNXa3RCRApqNVBGeUUwdS9qaCt3bmIwQ1VRYk16Y2UwcDhyVGUyQit2OVppYWJBSXVsakFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlNxeUk1OFptMzh6QUJwb1FoNVVuUHRUbzgvS1RBZkJnTlZIU01FR0RBV2dCU3F5STU4Wm0zOHpBQnAKb1FoNVVuUHRUbzgvS1RBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFERApSUVMzRjNDSzFiSG1jWkgydHFtZkYzTDJ3WlJqaXUxYkJGdHFKbUtEVVpjR281NlMxcG83bUFYeUVmYWJhOXBVCk5OM3czRXhzWVp6YytwSUFwS3kxNkZkenRWUHJ2RkpWUkpXd2JxQkVmNUFBQmhsNzRmeEZXZmxWeStscnd0WlUKTG5seFYzVm9jT2txVU5UZzBUTWNOTDFEb3dIOEZ4cTZicWthNUlyVk5CL0xFVkpjbE50RVRnb3hOMGVHc01neQpuY2V4VFZ2cDZnZmhYaEw2aGFWODA3RFhSWFJOZlQ1MVh3Yyt6N2I1MVJhR2wwRWJINFpySXRmamFzaWtZbEpYCnRyZjg1TE91QmFaalp4aFBSaXo0eS9VcnA0anhqdzNaZTFaUkZDVlpmTmJteXJ5MWliRUVuMFlRcmtpTG92RGQKTlNmRHVtV2c0dVZwUHg2VVRSM3EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  rules:
  - apiGroups:   ["netcracker.com"]
    apiVersions: ["*"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["sitemanagers"]
    scope:       "Namespaced"
  sideEffects: None
