{
 "title": "Paas-Geo-Monitor Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "inter",
    "label": "Interval",
    "query": "10s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(site_manager_requests_total, namespace)"
    }
   },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "peer_ip",
    "label": "Peer IP",
    "query": {
     "query": "label_values(paas_geo_monitor_bgp_peer{type=\"NodePeer\"},peer_ip)"
    }
   },
   {
    "name": "service_cidr",
    "label": "Service Network",
    "query": {
     "query": "label_values(paas_geo_monitor_bgp_route{source_type=\"BGPPeer\",type=\"FIB\"},destination)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Paas-geo-monitor thirdparties",
   "type": "table",
   "description": "Shows thirdparties versions for paas-geo-monitor",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group (label_replace(kube_pod_container_info{container=~\"calico-node\", cluster=~'$instance'}, \"version\", \"$2\", \"image\", \"(?:.+/)?([^:]+)(?::(.+))?\")) by (version, cluster, instance)",
     "legendFormat": "calico"
    },
    {
     "expr": "group (label_replace(kube_pod_container_info{container=~\"calico-apiserver\", cluster=~'$instance'}, \"version\", \"$2\", \"image\", \"(?:.+/)?([^:]+)(?::(.+))?\")) by (version, cluster, instance)\r\nor on()\r\ngroup (label_replace(kube_pod_container_info{container=~\"calico-node\", cluster=~'$instance'}, \"version\", \"Not installed\", \"\", \"\")) by (version, cluster, instance)",
     "legendFormat": "calico"
    }
   ]
  },
  {
   "title": "Peers dns status",
   "type": "timeseries",
   "description": "Indicates peers dns status",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (peer_name) (peer_dns_status{namespace='$namespace', cluster=~'$instance'})",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "Peers pod2service status",
   "type": "timeseries",
   "description": "Indicates peers pod to service status",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (peer_name) (peer_svc_status{namespace='$namespace', cluster=~'$instance'})",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "Peers pod2pod status",
   "type": "timeseries",
   "description": "Indicates peers pod to pod status",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (peer_name) (peer_pod_status{namespace='$namespace', cluster=~'$instance'})",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "Paas-geo-monitor Health",
   "type": "stat",
   "description": "Indicates paas-geo-monitor pod liveness",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max by (pod) (paas_geo_monitor_health{namespace='$namespace', cluster=~'$instance'})) or clamp_max(absent(max by (pod) (paas_geo_monitor_health{namespace='$namespace', cluster=~'$instance'})),0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Shows CPU usage per pod",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace='$namespace', cluster=~'$instance', pod=~'paas-geo-monitor.*', image!=''}[60s]))",
     "legendFormat": "CPU: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Shows Memory usage per pod",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace='$namespace', cluster=~'$instance', pod=~'paas-geo-monitor.*', image!=''})",
     "legendFormat": "Memory: {{pod}}"
    }
   ]
  },
  {
   "title": "Node BGP Peer Now",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max (paas_geo_monitor_bgp_peer{namespace='$namespace', cluster=~'$instance', peer_ip=~'$peer_ip', type='NodePeer'}) by(cluster, namespace, peer_ip)",
     "legendFormat": "{{cluster}} {{peer_ip}}"
    }
   ]
  },
  {
   "title": "Service Network Availability Now",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(max by (cluster, namespace, peer_ip, node) (paas_geo_monitor_bgp_route{cluster=~\"$instance\",namespace='$namespace',destination=\"$service_cidr\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Node BGP Peers",
   "type": "timeseries",
   "description": "Indicates peers dns status",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (cluster, namespace, peer_ip, node) (paas_geo_monitor_bgp_peer{namespace='$namespace', cluster=~'$instance', peer_ip=~'$peer_ip', type='NodePeer'})",
     "legendFormat": "{{node}} {{peer_ip}}"
    }
   ]
  },
  {
   "title": "Service Network Availability",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (cluster, namespace, peer_ip, node) (paas_geo_monitor_bgp_route{cluster=~\"$instance\",namespace='$namespace',destination=\"$service_cidr\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}