{
 "title": "SM Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "inter",
    "label": "Interval",
    "query": "10s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(site_manager_requests_total, namespace)"
    }
   },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(up, cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SM Health",
   "type": "stat",
   "description": "Indicates SM pod liveness",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max by (pod) (kube_pod_status_ready{namespace='$namespace', cluster=~'$instance', pod=~'site-manager.*', condition=\"true\"})) or clamp_max(absent(max by (pod) (kube_pod_status_ready{namespace='$namespace', cluster=~'$instance', pod=~'site-manager.*', condition=\"true\"})),0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "description": "Shows total HTTP request to SM pod per minute",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(code, pod) (increase(site_manager_requests_total{namespace='$namespace', cluster=~'$instance', url!='/metrics'}[1m]))",
     "legendFormat": "HTTP {{code}}: {{pod}} main SM"
    },
    {
     "expr": "sum by(code, pod) (increase(controller_runtime_webhook_requests_total{namespace='$namespace', cluster=~'$instance', url!='/metrics'}[1m]))",
     "legendFormat": "HTTP {{ code }}: {{pod}} webhook-controller"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Shows Memory usage per pod",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace='$namespace', cluster=~'$instance', pod=~'site-manager.*', image!='', container != ''})",
     "legendFormat": "Memory: {{pod}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Requests to each SM endpoint per second with 200 and 204 status codes",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(site_manager_request_duration_seconds_count{code=~\"204|200\", namespace='$namespace', cluster=~'$instance'}[60s])",
     "legendFormat": "{{ url }}: {{pod}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "description": "Shows number of bad status codes returned by SM pod",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(site_manager_request_duration_seconds_count{code!~\"204|200\", namespace='$namespace', cluster=~'$instance'}[60s])) OR on() vector(0)",
     "legendFormat": "errors: {{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Shows CPU usage per pod",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace='$namespace', cluster=~'$instance', pod=~'site-manager.*', image!='', container != ''}[60s]))",
     "legendFormat": "CPU: {{pod}}"
    }
   ]
  },
  {
   "title": "Average response time GET [60s]",
   "type": "timeseries",
   "description": "Shows average time which spend to response on GET requests",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(site_manager_request_duration_seconds_sum{code=~\"204|200\", method=\"GET\", namespace='$namespace', cluster=~'$instance'}[60s])\n/\nclamp_min(rate(site_manager_request_duration_seconds_count{code=~\"204|200\", method=\"GET\", namespace='$namespace', cluster=~'$instance'}[60s]), 1)",
     "legendFormat": "{{ url }}: {{pod}}"
    }
   ]
  },
  {
   "title": "Average response time POST [60s]",
   "type": "timeseries",
   "description": "Shows average time which spend to response on POST requests",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(site_manager_request_duration_seconds_sum{code=~\"204|200\", method=\"POST\", namespace='$namespace', cluster=~'$instance'}[60s])\n/\nclamp_min(rate(site_manager_request_duration_seconds_count{code=~\"204|200\", method=\"POST\", namespace='$namespace', cluster=~'$instance'}[60s]), 1)",
     "legendFormat": "{{ url }}: {{pod}}"
    }
   ]
  },
  {
   "title": "Average response time webhook endpoints",
   "type": "timeseries",
   "description": "Shows average time which spend to response on webhook requests",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(controller_runtime_webhook_latency_seconds_sum{namespace='$namespace', cluster=~'$instance'}[60s])\n/\nclamp_min(rate(controller_runtime_webhook_latency_seconds_count{namespace='$namespace', cluster=~'$instance'}[60s]), 1)",
     "legendFormat": "{{ webhook }}: {{pod}}"
    }
   ]
  },
  {
   "title": "Webhook requests per second",
   "type": "timeseries",
   "description": "Requests to each webhook endpoint per second",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(controller_runtime_webhook_latency_seconds_count{namespace='$namespace', cluster=~'$instance'}[60s])",
     "legendFormat": "{{ webhook }}: {{pod}}"
    }
   ]
  },
  {
   "title": "SM reconcile Rate",
   "type": "timeseries",
   "description": "Reconciliation results per second",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by(result, pod) (rate(controller_runtime_reconcile_total{namespace='$namespace', cluster=~'$instance'}[60s]))",
     "legendFormat": "{{ result }}: {{pod}}"
    }
   ]
  }
 ]
}