server:
  bind-address: 0.0.0.0
  bind-port: 8080

  # API extensions
  api:
    - name: no-wait
      default: false
      required: true

kubernetes:
  sm_group: "netcracker.com"
  sm_plural: "sitemanagers"
  sm_version: "v1"

  # Services defaults
  services:
    http_scheme: "http://"
    service_default_timeout: 200

testing:
  enabled: True
  token: "54321"
  sm_dict:
    services:
      serviceA:
        after: []
        allowedStandbyStateList:
        - up
        before: []
        namespace: serviceA-ns
        module: stateful
        parameters:
            healthzEndpoint: http://serviceA-site-2:8080/healthz
            ingressEndpoint: ""
            serviceEndpoint: http://serviceA-site-2:8080/sitemanager
        sequence:
        - standby
        - active
        timeout: 360
      serviceB:
        after: [serviceA]
        allowedStandbyStateList:
        - up
        before: []
        namespace: serviceB-ns
        module: stateful
        parameters:
            healthzEndpoint: http://serviceB-site-2:8080/healthz
            ingressEndpoint: ""
            serviceEndpoint: http://serviceB-site-2:8080/sitemanager
        sequence:
        - standby
        - active
        timeout: 360