namespace: site-manager

env:
  # set authentication mode
  FRONT_HTTP_AUTH: "Yes"
  BACK_HTTP_AUTH: "Yes"

  # set host and port for web service
  SM_WEB_HOST: "0.0.0.0"
  SM_WEB_PORT: 8080

  # set logging verbosity
  SM_DEBUG: "False"

  # set CRD parameters
  SM_GROUP: "netcracker.com"
  SM_PLURAL: "sitemanagers"
  SM_VERSION: "v2"

  # set default timeout for managed microservices
  SERVICE_DEFAULT_TIMEOUT: 200

  # set HTTP scheme for microservices
  HTTP_SCHEME: "http://"

serviceAccount:
  create: true
  name: site-manager-sa

image:
  repository: ghcr.io/netcracker/site-manager
  pullPolicy: Always
  tag: v1.0

ingress:
  create: true
  name: ""
