name: Benchmark check

on:
  push:
    branches:
      - '**'

jobs:
  measure-time:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        procedure: ["move", "stop"]
        sm-version: ["0.19.0", "0.20.0"]
    env:
      benchmark_dir: ./benchmark
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Docker login
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - name: Pull and tag SM images
        run: |
          docker pull ghcr.io/netcracker/sm-dummy:${{ matrix.sm-version }}
          docker pull ghcr.io/netcracker/site-manager:${{ matrix.sm-version }}
          docker tag ghcr.io/netcracker/sm-dummy:${{ matrix.sm-version }} sm-dummy
          docker tag ghcr.io/netcracker/site-manager:${{ matrix.sm-version }} site-manager
      - name: Test get images
        run: docker images
      - name: Copy benchmark files to not git directory
        run: cp -r ./ci/benchmark ${{ env.benchmark_dir }}
      - name: Checkout tags
        run: |
          git fetch --tags
          git checkout tags/${{ matrix.sm-version }}
      - name: test sm-client version
        run: cat version
      - name: Run docker compose
        run: docker-compose -f ${{ env.benchmark_dir }}/docker-compose.yaml up --detach
      - name: Test containers
        run: docker container ls
      - name: Measure the time
        run: ${{ env.benchmark_dir }}/measure_time.sh $procedure
      - name: Down docker compose
        run: docker-compose -f ${{ env.benchmark_dir }}/docker-compose.yaml down
