name: Build Artifacts
on:
  push:
    branches:
      - '**'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build Docker Image for site-manager
        run: docker build -t site-manager --no-cache site-manager
      - name: Build Docker Image for sm-client
        run: docker build -t sm-client -f Dockerfile-sc --no-cache .
      - name: Build Docker Image for paas-geo-monitor
        run: docker build -t paas-geo-monitor --no-cache paas-geo-monitor
      - name: Build Docker Image for sm-dummy
        run: docker build -t sm-dummy --no-cache tests/sm-dummy
      - name: Build Docker Image for sm-check
        run: docker build -t sm-check --no-cache sm-check
      - name: Check images
        run: docker images -a --digests

  multiplatform_build:
    strategy:
      matrix:
        component:
          - name: site-manager
            dir: site-manager
            file: Dockerfile
          - name: sm-client
            dir: .
            file: Dockerfile-sc
          - name: paas-geo-monitor
            dir: paas-geo-monitor
            file: Dockerfile
          - name: sm-dummy
            dir: tests/sm-dummy
            file: Dockerfile
          - name: sm-check
            dir: sm-check
            file: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ matrix.component.dir }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ matrix.component.name }}
