name: Build Artifacts
on:
  push:
    branches:
      - '**'
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Write Tag 
        run: |
            echo $GITHUB_REF_NAME > version
            echo "TAG=${GITHUB_REF_NAME}"
      - name: Build Docker Image for site-manager
        run: docker build -t site-manager -f Dockerfile-sm --no-cache .
      - name: Build Docker Image for sm-client
        run: docker build -t sm-client -f Dockerfile-sc --no-cache .
