name: Lint
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  sm-client-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install software
        run: pip install bandit
      - name: Security check with bandit
        run: bandit -r common sm_client sm-client
