name: Publish Artifacts
on:
  release:
    types: [created]
  push:
    branches:
      - 'main'
env:
  TAG_NAME: ${{ github.event.release.tag_name || (github.ref == 'refs/heads/main' && 'main') }}

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: site-manager
            dir: site-manager
            file: site-manager/Dockerfile
          - name: sm-client
            dir: .
            file: Dockerfile-sc
          - name: paas-geo-monitor
            dir: paas-geo-monitor
            file: paas-geo-monitor/Dockerfile
          - name: sm-dummy
            dir: tests/sm-dummy
            file: tests/sm-dummy/Dockerfile
          - name: sm-check
            dir: sm-check
            file: sm-check/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          context: ${{ matrix.component.dir }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/netcracker/${{ matrix.component.name }}:${{ env.TAG_NAME }}
          provenance: false
